"""
Base Repository - Generic async CRUD for SQLAlchemy models.

Repositories are the data-access layer: they know how to read and write a
single model to Postgres, and nothing else. Business logic (app/services/*)
should depend on repositories, not on raw SQLAlchemy queries.

Transaction convention: repositories `flush()` (to push pending SQL to
Postgres and get autogenerated IDs / trigger constraint checks) but never
`commit()`. The commit/rollback boundary lives in app.database.get_session(),
which wraps the whole FastAPI request in a single unit of work.
"""

from typing import Generic, TypeVar

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import Base

# Bound to Base so type checkers know ModelType is always a mapped model.
ModelType = TypeVar("ModelType", bound=Base)


class BaseRepository(Generic[ModelType]):
    """Generic async CRUD repository for a single SQLAlchemy model."""

    model: type[ModelType]

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    async def get_by_id(self, id: int) -> ModelType | None:
        """Fetch a single row by primary key, or None if it doesn't exist."""
        return await self.session.get(self.model, id)

    async def list(self, limit: int = 50, offset: int = 0) -> list[ModelType]:
        """Fetch a page of rows, ordered however the table naturally returns them."""
        result = await self.session.execute(select(self.model).limit(limit).offset(offset))
        return list(result.scalars().all())

    async def create(self, **kwargs) -> ModelType:
        """Insert a new row from keyword fields and return the persisted instance."""
        instance = self.model(**kwargs)
        self.session.add(instance)
        await self.session.flush()
        await self.session.refresh(instance)
        return instance

    async def update(self, instance: ModelType, **kwargs) -> ModelType:
        """Apply field updates to an already-loaded instance and persist them."""
        for key, value in kwargs.items():
            setattr(instance, key, value)
        await self.session.flush()
        await self.session.refresh(instance)
        return instance

    async def delete(self, instance: ModelType) -> None:
        """Delete an already-loaded instance."""
        await self.session.delete(instance)
        await self.session.flush()
