"""initial schema

Revision ID: 3c75f2d39e4f
Revises: 
Create Date: 2026-09-13 17:45:33.407765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c75f2d39e4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False, comment='Unique ID from Freehire API'),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('headquarters', sa.String(length=200), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_external_id'), 'companies', ['external_id'], unique=True)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index('ix_companies_name_industry', 'companies', ['name', 'industry'], unique=False)
    op.create_index(op.f('ix_companies_size'), 'companies', ['size'], unique=False)
    op.create_index('ix_companies_size_industry', 'companies', ['size', 'industry'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='Date of snapshot (UTC)'),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('total_companies', sa.Integer(), nullable=False),
    sa.Column('jobs_by_role', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jobs_by_skill', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jobs_by_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jobs_by_work_mode', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary_p25', sa.Numeric(), nullable=True),
    sa.Column('salary_p50', sa.Numeric(), nullable=True),
    sa.Column('salary_p75', sa.Numeric(), nullable=True),
    sa.Column('salary_by_role', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary_by_skill', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary_by_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_snapshots_date_desc', 'market_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_market_snapshots_snapshot_date'), 'market_snapshots', ['snapshot_date'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='External user ID from auth'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('work_mode_preference', sa.String(length=20), nullable=True, comment='remote, hybrid, onsite'),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('current_role', sa.String(length=200), nullable=True),
    sa.Column('current_company', sa.String(length=200), nullable=True),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_work_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary_expectation_min', sa.Numeric(), nullable=True),
    sa.Column('salary_expectation_max', sa.Numeric(), nullable=True),
    sa.Column('raw_cv_text', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    op.create_index(op.f('ix_profiles_location'), 'profiles', ['location'], unique=False)
    op.create_index('ix_profiles_location_experience', 'profiles', ['location', 'years_experience'], unique=False)
    op.create_index('ix_profiles_user_email', 'profiles', ['user_id', 'email'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Canonical role name'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='engineering, data, design, product, management'),
    sa.Column('level', sa.String(length=30), nullable=True, comment='junior, mid, senior, lead, principal, staff'),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_category'), 'roles', ['category'], unique=False)
    op.create_index('ix_roles_category_active', 'roles', ['category', 'is_active'], unique=False)
    op.create_index('ix_roles_category_level', 'roles', ['category', 'level'], unique=False)
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    op.create_index(op.f('ix_roles_level'), 'roles', ['level'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Canonical skill name'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='programming, framework, cloud, database, tool, soft'),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index('ix_skills_category_active', 'skills', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_skills_is_active'), 'skills', ['is_active'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=200), nullable=False),
    sa.Column('target_location', sa.String(length=200), nullable=True),
    sa.Column('target_work_mode', sa.String(length=20), nullable=True),
    sa.Column('analysis_level', sa.Enum('BASIC', 'STANDARD', 'FULL', name='analysislevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('market_fit_score', sa.Float(), nullable=True),
    sa.Column('market_fit_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_match_score', sa.Float(), nullable=True),
    sa.Column('experience_match_score', sa.Float(), nullable=True),
    sa.Column('location_match_score', sa.Float(), nullable=True),
    sa.Column('total_matching_jobs', sa.Integer(), nullable=False),
    sa.Column('analyzed_jobs_count', sa.Integer(), nullable=False),
    sa.Column('salary_p25', sa.Numeric(), nullable=True),
    sa.Column('salary_p50', sa.Numeric(), nullable=True),
    sa.Column('salary_p75', sa.Numeric(), nullable=True),
    sa.Column('salary_confidence', sa.Float(), nullable=True),
    sa.Column('salary_sample_size', sa.Integer(), nullable=False),
    sa.Column('skill_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unlocked_opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_overall', sa.Float(), nullable=True),
    sa.Column('confidence_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index('ix_analyses_profile_created', 'analyses', ['profile_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyses_profile_id'), 'analyses', ['profile_id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_index('ix_analyses_status_created', 'analyses', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyses_target_location'), 'analyses', ['target_location'], unique=False)
    op.create_index(op.f('ix_analyses_target_role'), 'analyses', ['target_role'], unique=False)
    op.create_index('ix_analyses_target_status', 'analyses', ['target_role', 'target_location', 'status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False, comment='Unique ID from Freehire API'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('work_mode', sa.String(length=20), nullable=True, comment='remote, hybrid, onsite'),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index('ix_jobs_company_posted', 'jobs', ['company_id', 'posted_at'], unique=False)
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=True)
    op.create_index(op.f('ix_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('ix_jobs_posted_at'), 'jobs', ['posted_at'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index('ix_jobs_title_location', 'jobs', ['title', 'location'], unique=False)
    op.create_index(op.f('ix_jobs_work_mode'), 'jobs', ['work_mode'], unique=False)
    op.create_index('ix_jobs_work_mode_posted', 'jobs', ['work_mode', 'posted_at'], unique=False)
    op.create_table('profile_experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('work_mode', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('skill_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['normalized_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profile_exp_profile_dates', 'profile_experience', ['profile_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_profile_exp_role_dates', 'profile_experience', ['role', 'start_date'], unique=False)
    op.create_index(op.f('ix_profile_experience_normalized_role_id'), 'profile_experience', ['normalized_role_id'], unique=False)
    op.create_index(op.f('ix_profile_experience_profile_id'), 'profile_experience', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_experience_role'), 'profile_experience', ['role'], unique=False)
    op.create_index(op.f('ix_profile_experience_start_date'), 'profile_experience', ['start_date'], unique=False)
    op.create_table('profile_skills',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=False, comment='1=beginner, 2=basic, 3=intermediate, 4=advanced, 5=expert'),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False, comment='cv, linkedin, manual, inferred'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'skill_id')
    )
    op.create_index('ix_profile_skills_primary', 'profile_skills', ['is_primary'], unique=False)
    op.create_index('ix_profile_skills_proficiency', 'profile_skills', ['proficiency'], unique=False)
    op.create_table('analysis_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='skill, role, location, certification, project'),
    sa.Column('target_name', sa.String(length=200), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='skill_id, role_id, etc.'),
    sa.Column('fit_score_delta', sa.Float(), nullable=True, comment='Projected fit score change'),
    sa.Column('salary_delta_p50', sa.Numeric(), nullable=True, comment='Projected median salary change'),
    sa.Column('unlocked_jobs_delta', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False, comment='Overall priority score'),
    sa.Column('effort_estimate', sa.String(length=20), nullable=True, comment='low, medium, high, very_high'),
    sa.Column('time_to_acquire', sa.String(length=50), nullable=True, comment="e.g., '2-3 months', '6 months'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_rec_analysis_priority', 'analysis_recommendations', ['analysis_id', 'priority'], unique=False)
    op.create_index('ix_analysis_rec_type', 'analysis_recommendations', ['type'], unique=False)
    op.create_index(op.f('ix_analysis_recommendations_analysis_id'), 'analysis_recommendations', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_recommendations_type'), 'analysis_recommendations', ['type'], unique=False)
    op.create_table('analysis_salary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('scenario_description', sa.String(length=500), nullable=True),
    sa.Column('p25', sa.Numeric(), nullable=True),
    sa.Column('p50', sa.Numeric(), nullable=True),
    sa.Column('p75', sa.Numeric(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False, comment='percentile, model, hybrid'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_salary_analysis_id'), 'analysis_salary', ['analysis_id'], unique=False)
    op.create_index('ix_analysis_salary_analysis_scenario', 'analysis_salary', ['analysis_id', 'scenario'], unique=False)
    op.create_index(op.f('ix_analysis_salary_scenario'), 'analysis_salary', ['scenario'], unique=False)
    op.create_table('analysis_skill_gaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False, comment='Composite priority: demand × match_impact × salary_impact'),
    sa.Column('market_demand', sa.Float(), nullable=False, comment='Frequency in target role postings (0-1)'),
    sa.Column('match_impact', sa.Float(), nullable=False, comment='How much this skill improves fit score (0-1)'),
    sa.Column('salary_impact', sa.Float(), nullable=False, comment='Salary premium associated with this skill (0-1)'),
    sa.Column('accessibility', sa.Float(), nullable=True, comment='Learning accessibility estimate (0-1)'),
    sa.Column('jobs_requiring', sa.Integer(), nullable=False),
    sa.Column('jobs_matching_with', sa.Integer(), nullable=False),
    sa.Column('unlocked_jobs_count', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=True),
    sa.Column('learning_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_gaps_analysis_priority', 'analysis_skill_gaps', ['analysis_id', 'priority_score'], unique=False)
    op.create_index('ix_analysis_gaps_skill', 'analysis_skill_gaps', ['skill_id'], unique=False)
    op.create_index(op.f('ix_analysis_skill_gaps_analysis_id'), 'analysis_skill_gaps', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_skill_gaps_skill_id'), 'analysis_skill_gaps', ['skill_id'], unique=False)
    op.create_table('job_roles',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False, comment='extracted, inferred, normalized, manual'),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'role_id'),
    sa.UniqueConstraint('job_id', 'role_id', name='uq_job_role')
    )
    op.create_index(op.f('ix_job_roles_job_id'), 'job_roles', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_roles_role_id'), 'job_roles', ['role_id'], unique=False)
    op.create_index('ix_job_roles_source', 'job_roles', ['source'], unique=False)
    op.create_table('job_skills',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False, comment='extracted, inferred, normalized, manual'),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id'),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skill')
    )
    op.create_index(op.f('ix_job_skills_is_required'), 'job_skills', ['is_required'], unique=False)
    op.create_index(op.f('ix_job_skills_job_id'), 'job_skills', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_skills_skill_id'), 'job_skills', ['skill_id'], unique=False)
    op.create_index('ix_job_skills_skill_required', 'job_skills', ['skill_id', 'is_required'], unique=False)
    op.create_index('ix_job_skills_source', 'job_skills', ['source'], unique=False)
    op.create_table('salary_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('min_salary', sa.Numeric(), nullable=True, comment='Minimum annual salary in USD'),
    sa.Column('max_salary', sa.Numeric(), nullable=True, comment='Maximum annual salary in USD'),
    sa.Column('median_salary', sa.Numeric(), nullable=True, comment='Median/expected annual salary in USD'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Original currency code'),
    sa.Column('period', sa.String(length=20), nullable=False, comment='Original period: yearly, monthly, hourly'),
    sa.Column('source', sa.String(length=30), nullable=False, comment='posted, estimated, glassdoor, etc.'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence in normalization (0.0-1.0)'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_salary_obs_currency_period', 'salary_observations', ['currency', 'period'], unique=False)
    op.create_index('ix_salary_obs_job_currency', 'salary_observations', ['job_id', 'currency'], unique=False)
    op.create_index('ix_salary_obs_median', 'salary_observations', ['median_salary'], unique=False)
    op.create_index(op.f('ix_salary_observations_currency'), 'salary_observations', ['currency'], unique=False)
    op.create_index(op.f('ix_salary_observations_job_id'), 'salary_observations', ['job_id'], unique=False)
    op.create_index(op.f('ix_salary_observations_period'), 'salary_observations', ['period'], unique=False)
    op.create_index(op.f('ix_salary_observations_source'), 'salary_observations', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_observations_source'), table_name='salary_observations')
    op.drop_index(op.f('ix_salary_observations_period'), table_name='salary_observations')
    op.drop_index(op.f('ix_salary_observations_job_id'), table_name='salary_observations')
    op.drop_index(op.f('ix_salary_observations_currency'), table_name='salary_observations')
    op.drop_index('ix_salary_obs_median', table_name='salary_observations')
    op.drop_index('ix_salary_obs_job_currency', table_name='salary_observations')
    op.drop_index('ix_salary_obs_currency_period', table_name='salary_observations')
    op.drop_table('salary_observations')
    op.drop_index('ix_job_skills_source', table_name='job_skills')
    op.drop_index('ix_job_skills_skill_required', table_name='job_skills')
    op.drop_index(op.f('ix_job_skills_skill_id'), table_name='job_skills')
    op.drop_index(op.f('ix_job_skills_job_id'), table_name='job_skills')
    op.drop_index(op.f('ix_job_skills_is_required'), table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index('ix_job_roles_source', table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_role_id'), table_name='job_roles')
    op.drop_index(op.f('ix_job_roles_job_id'), table_name='job_roles')
    op.drop_table('job_roles')
    op.drop_index(op.f('ix_analysis_skill_gaps_skill_id'), table_name='analysis_skill_gaps')
    op.drop_index(op.f('ix_analysis_skill_gaps_analysis_id'), table_name='analysis_skill_gaps')
    op.drop_index('ix_analysis_gaps_skill', table_name='analysis_skill_gaps')
    op.drop_index('ix_analysis_gaps_analysis_priority', table_name='analysis_skill_gaps')
    op.drop_table('analysis_skill_gaps')
    op.drop_index(op.f('ix_analysis_salary_scenario'), table_name='analysis_salary')
    op.drop_index('ix_analysis_salary_analysis_scenario', table_name='analysis_salary')
    op.drop_index(op.f('ix_analysis_salary_analysis_id'), table_name='analysis_salary')
    op.drop_table('analysis_salary')
    op.drop_index(op.f('ix_analysis_recommendations_type'), table_name='analysis_recommendations')
    op.drop_index(op.f('ix_analysis_recommendations_analysis_id'), table_name='analysis_recommendations')
    op.drop_index('ix_analysis_rec_type', table_name='analysis_recommendations')
    op.drop_index('ix_analysis_rec_analysis_priority', table_name='analysis_recommendations')
    op.drop_table('analysis_recommendations')
    op.drop_index('ix_profile_skills_proficiency', table_name='profile_skills')
    op.drop_index('ix_profile_skills_primary', table_name='profile_skills')
    op.drop_table('profile_skills')
    op.drop_index(op.f('ix_profile_experience_start_date'), table_name='profile_experience')
    op.drop_index(op.f('ix_profile_experience_role'), table_name='profile_experience')
    op.drop_index(op.f('ix_profile_experience_profile_id'), table_name='profile_experience')
    op.drop_index(op.f('ix_profile_experience_normalized_role_id'), table_name='profile_experience')
    op.drop_index('ix_profile_exp_role_dates', table_name='profile_experience')
    op.drop_index('ix_profile_exp_profile_dates', table_name='profile_experience')
    op.drop_table('profile_experience')
    op.drop_index('ix_jobs_work_mode_posted', table_name='jobs')
    op.drop_index(op.f('ix_jobs_work_mode'), table_name='jobs')
    op.drop_index('ix_jobs_title_location', table_name='jobs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_posted_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_location'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_index('ix_jobs_company_posted', table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_analyses_target_status', table_name='analyses')
    op.drop_index(op.f('ix_analyses_target_role'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_target_location'), table_name='analyses')
    op.drop_index('ix_analyses_status_created', table_name='analyses')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_profile_id'), table_name='analyses')
    op.drop_index('ix_analyses_profile_created', table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_active'), table_name='skills')
    op.drop_index('ix_skills_category_active', table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_level'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.drop_index('ix_roles_category_level', table_name='roles')
    op.drop_index('ix_roles_category_active', table_name='roles')
    op.drop_index(op.f('ix_roles_category'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index('ix_profiles_user_email', table_name='profiles')
    op.drop_index('ix_profiles_location_experience', table_name='profiles')
    op.drop_index(op.f('ix_profiles_location'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_market_snapshots_snapshot_date'), table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_date_desc', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('ix_companies_size_industry', table_name='companies')
    op.drop_index(op.f('ix_companies_size'), table_name='companies')
    op.drop_index('ix_companies_name_industry', table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_external_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
